---
title: "Election Results Visualization with ggplot2 - Map"
author: "Dennis Tseng"
date: "2020/01/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=TRUE,warning=FALSE,message=FALSE}
# Package names
packages <- c('tidyverse','sf','jsonlite','ggparliament','maps',
              'geojson','geojsonio','geojsonsf','cartogram')

# Install packages not yet installed
installed_packages <- packages %in% rownames(installed.packages())
if (any(installed_packages == FALSE)) {
  install.packages(packages[!installed_packages])
}

# Packages loading
invisible(lapply(packages, library, character.only = TRUE))

# devtools::install_github("olihawkins/clhex")
library(clhex)
```

## Background Map


```{r,echo=TRUE,warning=FALSE,message=FALSE}
### read simplified shp
dirpath_data <- "Sharing/data/"
sf_county_shp_small <- st_read(str_c(dirpath_data, "geo_raw/COUNTY_MOI_1081121/COUNTY_MOI_1081121.shp"))
sf_county_shp_small %>%
  ggplot() + geom_sf()

### read geojson
county_json_raw <- read_json(str_c(dirpath_data, "geo_raw/tawian_county.json"))

### there may be encoding problem on windows, if so then use iconv()
sf_county_geojson_simplified <- county_json_raw %>% as.json() %>% 
  geojson_sf() # %>% 
  # mutate(COUNTYNAME = iconv(COUNTYNAME, "UTF-8", "BIG-5") )

sf_county_geojson_simplified %>%
  ggplot() + geom_sf()

### add longitude and latitude constraint
sf_county_geojson_simplified %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot() + geom_sf()
```

## Choropleth

```{r,echo=TRUE,warning=FALSE,message=FALSE}
### read result data
df_president_county_result <- read_csv(str_c(dirpath_data, "2020/df_president_county_result_raw.csv")) %>%
  dplyr::select(place, number, party, name, vote, per, vote_place) 

### filter KMT presidential vote
df_president_county_result_blue <-
  df_president_county_result %>% 
  filter(number == 2)

### add centroid column for further use
sf_county_centroid =
  sf_county_geojson_simplified %>%
  st_centroid(of_largest_polygon = T)

df_coordination = 
  sf_county_centroid %>% 
  st_coordinates()

### join vote & Taiwan sf data
sf_county_president <- 
  sf_county_geojson_simplified %>% 
  left_join(df_president_county_result_blue, by = c("COUNTYNAME" = "place")) %>%
  mutate(rn = row_number()) %>%
  mutate(x_centroid = df_coordination[,"X"],
         y_centroid = df_coordination[,"Y"])

### raw plot
sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot()+
  geom_sf(size = 0.2, aes(fill = per))+
  scale_fill_gradient(low = "#56B1F7", high = "#132B43")

### add text label
sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot()+
  geom_sf(size = 0.2, aes(fill = per)) +
  geom_text(
    aes(
      x=x_centroid,y=y_centroid,
      label = round(per, 2)
    ), size=3
  ) +
  scale_fill_gradientn(colors = c("white","#CCCCEE","#9999DD","#4141EF")) +
  coord_sf(datum = NA)+
  ggthemes::theme_map()

### save plots for ggsave
plot_kmt_president <-
  sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot()+
  geom_sf(size = 0.2, aes(fill = per)) +
  geom_text(
    aes(
      x=x_centroid,y=y_centroid,
      label = round(per, 2)
    ), size=3
  ) +
  scale_fill_gradientn(colors = c("white","#CCCCEE","#9999DD","#4141EF")) +
  coord_sf(datum = NA)+
  ggthemes::theme_map()

### use ggsave to save plots
# ggplot2::ggsave(filename = str_c(dirpath_data, "plot_kmt_president.svg"),plot = plot_kmt_president)
```

## Dot Distribution Map/Bubble Map

```{r,echo=TRUE,warning=FALSE,message=FALSE}
### get data
df_city_taiwan <- world.cities %>% 
  filter(country.etc=="Taiwan") %>% as_tibble()

df_city_taiwan %>% head(3)

### plotting: each point equals a city
sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot() +
  geom_sf(size = 0.2) +
  geom_point(data=df_city_taiwan, aes(x=long, y=lat)) +
  theme_void()

### plotting: city population size matters
sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  ggplot() +
  geom_sf(size = 0.2) +
  geom_point(data=df_city_taiwan, aes(x=long, y=lat, size = pop)) +
  theme_void()
```

## Cartogram

```{r,echo=TRUE,warning=FALSE,message=FALSE}
### create sp data
sf_county_president_carto <- sf_county_president %>%
  st_crop(xmin=119,xmax=123,ymin=20,ymax=26) %>%
  st_transform(crs = 3828)

### use cartogram package
library(cartogram)
president_cartogram <- cartogram_cont(sf_county_president_carto, "vote_place", itermax=5)

### plot
president_cartogram %>%
  ggplot() +
  geom_sf(aes(fill = per) , size=0, alpha=0.9) +
  scale_fill_gradientn(colors = c("white","#CCCCEE","#9999DD","#4141EF")) +
  coord_sf() +
  theme_void()
```

## Parliament Plot

```{r,echo=TRUE,warning=FALSE,message=FALSE}
library(ggparliament)
### get data
df_parliament_summary_raw <- read_rds(str_c(dirpath_data, "2020/df_parliament_summary_raw.rds"))
# df_parliament_summary_raw <- read_csv(str_c(dirpath_data, "2020/df_parliament_summary_raw.csv"))

### take a look
df_parliament_summary_raw %>% head(5) %>%
  kableExtra::kable("html") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

### use ggparliament::parliament_data to create cooridinate system & theta
df_parliament_final <- parliament_data(election_data = df_parliament_summary_raw,
                                       type = "semicircle",
                                       parl_rows = 6,
                                       party_seats = df_parliament_summary_raw$seats)

df_parliament_final %>% head(5) %>%
  dplyr::select(party_long,party_short,seats,government,colour,x,y,row,theta) %>%
  kableExtra::kable("html") %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))

### plot: simple
df_parliament_final %>%
  ggplot(aes(x, y, colour = party_short)) +
  geom_parliament_seats(size = 5) 

### plot: complete
df_parliament_final %>%
  ggplot(aes(x, y, colour = party_short)) +
  geom_parliament_seats(size = 5) + 
  geom_highlight_government(government == 1) +
  geom_parliament_bar(colour = colour, party = party_long) + 
  draw_majoritythreshold(n = 57, label = TRUE, type = 'semicircle')+
  theme_ggparliament() +
  #other aesthetics
  labs(colour = NULL, 
       title = "Taiwan Legislative Yuan",
       subtitle = "Party that controls the Legislative Yuan highlighted.") +
  scale_colour_manual(values = unique(df_parliament_final$colour), 
                      limits = unique(df_parliament_final$party_short)) 
### 其他可以選的類型
#type = "horseshoe", "semicircle", "circle", "classroom", "opposing_benches"
``` 

## Hexmap/Tilegram

```{r,echo=TRUE,warning=FALSE,message=FALSE}
### create hexJSON based on constituency
library(clhex)
df_legis_constituency <- read_rds(str_c(dirpath_data, "2020/df_legis_constituency.rds"))
hex_test <- create_hexjson(df_legis_constituency)

### 我已經create過了
# create_and_save_hexjson(df_legis_constituency, str_c(dirpath_data, "2020/output.hexjson"))

### go to https://olihawkins.com/project/hexjson-editor/ and download data from there

### import data
json_2020 <- geojson_read(str_c(dirpath_data, "2020/hexmap.geojson"))
sf_2020 <- json_2020 %>% as.json() %>% geojson_sf()

### plot
sf_2020 %>%
  ggplot() +
  geom_sf(size = 0, aes(fill = value)) +
  scale_fill_manual(values=c("#4141EF", "#33AE33", "#808080")) +
  coord_sf(datum = NA) +
  ggthemes::theme_map() +
  theme(legend.position = "null")
```
